# noinspection SqlNoDataSourceInspectionForFile

-- THIS IS NOT A CrateDB.sql FILE
-- THIS FILE WAS CREATED FOR MySQL
--
-- EXPERIMENTAL
-- This file will use BINARY for Host and Service names

INSERT INTO `statusengine_host_statehistory_bin` (`hostname`,
                                                  `state_time`,
                                                  `state_change`,
                                                  `state`,
                                                  `is_hardstate`,
                                                  `current_check_attempt`,
                                                  `max_check_attempts`,
                                                  `last_state`,
                                                  `last_hard_state`,
                                                  `output`,
                                                  `long_output`)
SELECT UNHEX(REPLACE(`hostname`, "-", "")),
       `state_time`,
       `state_change`,
       `state`,
       `is_hardstate`,
       `current_check_attempt`,
       `max_check_attempts`,
       `last_state`,
       `last_hard_state`,
       `output`,
       `long_output`
FROM `statusengine_host_statehistory`;


INSERT IGNORE INTO `statusengine_service_statehistory_bin` (`hostname`,
                                                            `service_description`,
                                                            `state_time`,
                                                            `state_change`,
                                                            `state`,
                                                            `is_hardstate`,
                                                            `current_check_attempt`,
                                                            `max_check_attempts`,
                                                            `last_state`,
                                                            `last_hard_state`,
                                                            `output`,
                                                            `long_output`)
SELECT UNHEX(REPLACE(`hostname`, "-", "")),
       UNHEX(REPLACE(`service_description`, "-", "")),
       `state_time`,
       `state_change`,
       `state`,
       `is_hardstate`,
       `current_check_attempt`,
       `max_check_attempts`,
       `last_state`,
       `last_hard_state`,
       `output`,
       `long_output`
FROM `statusengine_service_statehistory`;


INSERT IGNORE INTO `statusengine_hostchecks_bin` (`hostname`,
                                                  `state`,
                                                  `is_hardstate`,
                                                  `start_time`,
                                                  `end_time`,
                                                  `output`,
                                                  `timeout`,
                                                  `early_timeout`,
                                                  `latency`,
                                                  `execution_time`,
                                                  `perfdata`,
                                                  `command`,
                                                  `current_check_attempt`,
                                                  `max_check_attempts`,
                                                  `long_output`)
SELECT UNHEX(REPLACE(`hostname`, "-", "")),
       `state`,
       `is_hardstate`,
       `start_time`,
       `end_time`,
       `output`,
       `timeout`,
       `early_timeout`,
       `latency`,
       `execution_time`,
       `perfdata`,
       `command`,
       `current_check_attempt`,
       `max_check_attempts`,
       `long_output`
FROM `statusengine_hostchecks`;


INSERT IGNORE INTO `statusengine_servicechecks_bin` (`hostname`,
                                                     `service_description`,
                                                     `state`,
                                                     `is_hardstate`,
                                                     `start_time`,
                                                     `end_time`,
                                                     `output`,
                                                     `timeout`,
                                                     `early_timeout`,
                                                     `latency`,
                                                     `execution_time`,
                                                     `perfdata`,
                                                     `command`,
                                                     `current_check_attempt`,
                                                     `max_check_attempts`,
                                                     `long_output`)
SELECT UNHEX(REPLACE(`hostname`, "-", "")),
       UNHEX(REPLACE(`service_description`, "-", "")),
       `state`,
       `is_hardstate`,
       `start_time`,
       `end_time`,
       `output`,
       `timeout`,
       `early_timeout`,
       `latency`,
       `execution_time`,
       `perfdata`,
       `command`,
       `current_check_attempt`,
       `max_check_attempts`,
       `long_output`
FROM `statusengine_servicechecks`;


INSERT IGNORE INTO `statusengine_host_notifications_bin` (`hostname`,
                                                          `contact_name`,
                                                          `command_name`,
                                                          `command_args`,
                                                          `state`,
                                                          `start_time`,
                                                          `end_time`,
                                                          `reason_type`,
                                                          `output`,
                                                          `ack_author`,
                                                          `ack_data`)
SELECT UNHEX(REPLACE(`hostname`, "-", "")),
       `contact_name`,
       `command_name`,
       `command_args`,
       `state`,
       `start_time`,
       `end_time`,
       `reason_type`,
       `output`,
       `ack_author`,
       `ack_data`
FROM `statusengine_host_notifications`;


INSERT IGNORE INTO `statusengine_service_notifications_bin` (`hostname`,
                                                             `service_description`,
                                                             `contact_name`,
                                                             `command_name`,
                                                             `command_args`,
                                                             `state`,
                                                             `start_time`,
                                                             `end_time`,
                                                             `reason_type`,
                                                             `output`,
                                                             `ack_author`,
                                                             `ack_data`)
SELECT UNHEX(REPLACE(`hostname`, "-", "")),
       UNHEX(REPLACE(`service_description`, "-", "")),
       `contact_name`,
       `command_name`,
       `command_args`,
       `state`,
       `start_time`,
       `end_time`,
       `reason_type`,
       `output`,
       `ack_author`,
       `ack_data`
FROM `statusengine_service_notifications`;

INSERT IGNORE INTO `statusengine_host_acknowledgements_bin` (`hostname`,
                                                             `state`,
                                                             `author_name`,
                                                             `comment_data`,
                                                             `entry_time`,
                                                             `acknowledgement_type`,
                                                             `is_sticky`,
                                                             `persistent_comment`,
                                                             `notify_contacts`)
SELECT UNHEX(REPLACE(`hostname`, "-", "")),
       `state`,
       `author_name`,
       `comment_data`,
       `entry_time`,
       `acknowledgement_type`,
       `is_sticky`,
       `persistent_comment`,
       `notify_contacts`
FROM `statusengine_host_acknowledgements`;


INSERT IGNORE INTO `statusengine_service_acknowledgements_bin` (`hostname`,
                                                                `service_description`,
                                                                `state`,
                                                                `author_name`,
                                                                `comment_data`,
                                                                `entry_time`,
                                                                `acknowledgement_type`,
                                                                `is_sticky`,
                                                                `persistent_comment`,
                                                                `notify_contacts`)
SELECT UNHEX(REPLACE(`hostname`, "-", "")),
       UNHEX(REPLACE(`service_description`, "-", "")),
       `state`,
       `author_name`,
       `comment_data`,
       `entry_time`,
       `acknowledgement_type`,
       `is_sticky`,
       `persistent_comment`,
       `notify_contacts`
FROM `statusengine_service_acknowledgements`;


INSERT IGNORE INTO `statusengine_service_acknowledgements_bin` (`hostname`,
                                                                `service_description`,
                                                                `state`,
                                                                `author_name`,
                                                                `comment_data`,
                                                                `entry_time`,
                                                                `acknowledgement_type`,
                                                                `is_sticky`,
                                                                `persistent_comment`,
                                                                `notify_contacts`)
SELECT UNHEX(REPLACE(`hostname`, "-", "")),
       UNHEX(REPLACE(`service_description`, "-", "")),
       `state`,
       `author_name`,
       `comment_data`,
       `entry_time`,
       `acknowledgement_type`,
       `is_sticky`,
       `persistent_comment`,
       `notify_contacts`
FROM `statusengine_service_acknowledgements`;


INSERT IGNORE INTO `statusengine_host_downtimehistory_bin` (`hostname`,
                                                            `entry_time`,
                                                            `author_name`,
                                                            `comment_data`,
                                                            `internal_downtime_id`,
                                                            `triggered_by_id`,
                                                            `is_fixed`,
                                                            `duration`,
                                                            `scheduled_start_time`,
                                                            `scheduled_end_time`,
                                                            `was_started`,
                                                            `actual_start_time`,
                                                            `actual_end_time`,
                                                            `was_cancelled`,
                                                            `node_name`)
SELECT UNHEX(REPLACE(`hostname`, "-", "")),
       `entry_time`,
       `author_name`,
       `comment_data`,
       `internal_downtime_id`,
       `triggered_by_id`,
       `is_fixed`,
       `duration`,
       `scheduled_start_time`,
       `scheduled_end_time`,
       `was_started`,
       `actual_start_time`,
       `actual_end_time`,
       `was_cancelled`,
       `node_name`
FROM `statusengine_host_downtimehistory`;


INSERT IGNORE INTO `statusengine_host_scheduleddowntimes_bin` (`hostname`,
                                                               `entry_time`,
                                                               `author_name`,
                                                               `comment_data`,
                                                               `internal_downtime_id`,
                                                               `triggered_by_id`,
                                                               `is_fixed`,
                                                               `duration`,
                                                               `scheduled_start_time`,
                                                               `scheduled_end_time`,
                                                               `was_started`,
                                                               `actual_start_time`,
                                                               `node_name`)
SELECT UNHEX(REPLACE(`hostname`, "-", "")),
       `entry_time`,
       `author_name`,
       `comment_data`,
       `internal_downtime_id`,
       `triggered_by_id`,
       `is_fixed`,
       `duration`,
       `scheduled_start_time`,
       `scheduled_end_time`,
       `was_started`,
       `actual_start_time`,
       `node_name`
FROM `statusengine_host_scheduleddowntimes`;


INSERT IGNORE INTO `statusengine_service_downtimehistory_bin` (`hostname`,
                                                               `service_description`,
                                                               `entry_time`,
                                                               `author_name`,
                                                               `comment_data`,
                                                               `internal_downtime_id`,
                                                               `triggered_by_id`,
                                                               `is_fixed`,
                                                               `duration`,
                                                               `scheduled_start_time`,
                                                               `scheduled_end_time`,
                                                               `was_started`,
                                                               `actual_start_time`,
                                                               `actual_end_time`,
                                                               `was_cancelled`,
                                                               `node_name`)
SELECT UNHEX(REPLACE(`hostname`, "-", "")),
       UNHEX(REPLACE(`service_description`, "-", "")),
       `entry_time`,
       `author_name`,
       `comment_data`,
       `internal_downtime_id`,
       `triggered_by_id`,
       `is_fixed`,
       `duration`,
       `scheduled_start_time`,
       `scheduled_end_time`,
       `was_started`,
       `actual_start_time`,
       `actual_end_time`,
       `was_cancelled`,
       `node_name`
FROM `statusengine_service_downtimehistory`;


INSERT IGNORE INTO `statusengine_service_downtimehistory_bin` (`hostname`,
                                                               `service_description`,
                                                               `entry_time`,
                                                               `author_name`,
                                                               `comment_data`,
                                                               `internal_downtime_id`,
                                                               `triggered_by_id`,
                                                               `is_fixed`,
                                                               `duration`,
                                                               `scheduled_start_time`,
                                                               `scheduled_end_time`,
                                                               `was_started`,
                                                               `actual_start_time`,
                                                               `node_name`)
SELECT UNHEX(REPLACE(`hostname`, "-", "")),
       UNHEX(REPLACE(`service_description`, "-", "")),
       `entry_time`,
       `author_name`,
       `comment_data`,
       `internal_downtime_id`,
       `triggered_by_id`,
       `is_fixed`,
       `duration`,
       `scheduled_start_time`,
       `scheduled_end_time`,
       `was_started`,
       `actual_start_time`,
       `node_name`
FROM `statusengine_service_scheduleddowntimes`;


INSERT IGNORE INTO `statusengine_perfdata_bin` (`hostname`,
                                                `service_description`,
                                                `label`,
                                                `timestamp`,
                                                `timestamp_unix`,
                                                `value`,
                                                `unit`)
SELECT UNHEX(REPLACE(`hostname`, "-", "")),
       UNHEX(REPLACE(`service_description`, "-", "")),
       `label`,
       `timestamp`,
       `timestamp_unix`,
       `value`,
       `unit`
FROM `statusengine_perfdata`;
